//! Provides interfaces for rebuilding snapshot storages

use {
    super::SnapshotError,
    crate::serde_snapshot::{SerdeObsoleteAccounts, StorageListItem, remap_append_vec_file},
    agave_fs::FileInfo,
    log::*,
    solana_accounts_db::{
        ObsoleteAccounts,
        account_storage::AccountStorageMap,
        account_storage_entry::AccountStorageEntry,
        accounts_db::{AccountsFileId, AtomicAccountsFileId},
        accounts_file::AccountsFile,
    },
    solana_clock::Slot,
    std::{
        collections::HashMap,
        path::PathBuf,
        str::FromStr as _,
        sync::{Arc, atomic::Ordering},
        time::{Duration, Instant},
    },
};

const PROGRESS_LOG_INTERVAL: Duration = Duration::from_secs(2);

/// Holds state for rebuilding snapshot storages
#[derive(Debug)]
pub(crate) struct SnapshotStorageRebuilder {
    /// Container for storing rebuilt snapshot storages
    storage: AccountStorageMap,
    /// Tracks next append_vec_id
    next_append_vec_id: Arc<AtomicAccountsFileId>,
    /// Tracks the number of collisions in AccountsFileId
    num_collisions: usize,
    /// Number of storage slots that have been rebuilt so far
    processed_slot_count: usize,
}

impl SnapshotStorageRebuilder {
    fn new(next_append_vec_id: Arc<AtomicAccountsFileId>) -> Self {
        Self {
            storage: AccountStorageMap::default(),
            next_append_vec_id,
            num_collisions: 0,
            processed_slot_count: 0,
        }
    }

    /// Rebuilds the account storages from a snapshot archive.
    pub(crate) fn rebuild_storages_from_snapshot_archive(
        files: impl IntoIterator<Item = FileInfo>,
        next_append_vec_id: Arc<AtomicAccountsFileId>,
    ) -> Result<AccountStorageMap, SnapshotError> {
        let mut rebuilder = Self::new(next_append_vec_id);
        let mut previous_log_time = Instant::now();

        for file_info in files {
            let filename = file_info.path.file_name().unwrap().to_str().unwrap();
            if let Ok((slot, id)) = get_slot_and_append_vec_id(filename) {
                if filename.ends_with(".meta") || filename.ends_with(".data") {
                    return Err(SnapshotError::RebuildStorages(
                        "snapshot archives must contain AppendVec storages".to_owned(),
                    ));
                }
                // A snapshot archive only contains storages in AppendVec format.
                // And never contains separate ObsoleteAccounts information.
                // The IDs may overlap though, if the full and incremental snapshots
                // were generated by different nodes.
                let (remapped_id, remapped_file_info) = remap_append_vec_file(
                    slot,
                    id,
                    file_info,
                    &rebuilder.next_append_vec_id,
                    &mut rebuilder.num_collisions,
                )?;
                let accounts_file = AccountsFile::new_for_startup(remapped_file_info)?;
                let storage_entry = AccountStorageEntry::new_existing(
                    slot,
                    remapped_id,
                    accounts_file,
                    ObsoleteAccounts::default(),
                );

                rebuilder.insert_storage(slot, Arc::new(storage_entry))?;
                rebuilder.processed_slot_count += 1;
            }
            rebuilder.maybe_log_progress(&mut previous_log_time);
        }

        Ok(rebuilder.storage)
    }

    /// Rebuilds the account storages from local state.
    pub(crate) fn rebuild_storages_from_local_state(
        files: impl IntoIterator<Item = FileInfo>,
        next_append_vec_id: Arc<AtomicAccountsFileId>,
        mut obsolete_accounts: HashMap<Slot, SerdeObsoleteAccounts>,
        mut expected_storages: HashMap<(Slot, AccountsFileId), StorageListItem>,
    ) -> Result<AccountStorageMap, SnapshotError> {
        let mut rebuilder = Self::new(next_append_vec_id);
        let mut split_files: HashMap<PathBuf, FileInfo> = HashMap::new();
        let mut previous_log_time = Instant::now();

        for file_info in files {
            let filename = file_info.path.file_name().unwrap().to_str().unwrap();
            if let Ok((slot, id)) = get_slot_and_append_vec_id(filename) {
                let id = AccountsFileId::try_from(id).unwrap();
                let expected = expected_storages.get(&(slot, id)).copied()
                    .filter(|item| item.matches_filename(filename))
                    .ok_or_else(|| SnapshotError::RebuildStorages(format!(
                        "unexpected storage file '{}'", file_info.path.display(),
                    )))?;
                let (meta, data) = match expected {
                    StorageListItem::AppendVec { .. } => (file_info, None),
                    StorageListItem::Split { has_data_file: false, .. } => (file_info, None),
                    StorageListItem::Split { has_data_file: true, .. } => {
                        let base_path = file_info.path.with_extension("");
                        let Some(other) = split_files.remove(&base_path) else {
                            split_files.insert(base_path, file_info);
                            rebuilder.maybe_log_progress(&mut previous_log_time);
                            continue;
                        };
                        if filename.ends_with(".meta") {
                            (file_info, Some(other))
                        } else {
                            (other, Some(file_info))
                        }
                    }
                };
                // Validate obsolete accounts before opening either storage format.
                let obsolete_accounts = obsolete_accounts.remove(&slot).map(|accounts| accounts.into_tuple());
                let obsolete_accounts =
                    if let Some((obsolete_accounts, obsolete_id, _bytes)) = obsolete_accounts {
                        if obsolete_id != id {
                            return Err(SnapshotError::MismatchedAccountsFileId(id, obsolete_id));
                        }
                        obsolete_accounts
                    } else {
                        ObsoleteAccounts::default()
                    };
                let accounts_file = match expected {
                    StorageListItem::AppendVec { .. } => AccountsFile::new_for_startup(meta)?,
                    StorageListItem::Split { .. } => AccountsFile::new_split_for_startup(meta, data)?,
                };
                let storage_entry =
                    AccountStorageEntry::new_existing(slot, id, accounts_file, obsolete_accounts);

                // Keep track of the highest append_vec_id in the system, so the future append_vecs
                // can be assigned to unique IDs.  This is only needed when loading from local
                // state.  When loading from a snapshot archive, the max of the appendvec IDs is
                // updated in remap_append_vec_file(), which is not in the from_local_state route.
                rebuilder
                    .next_append_vec_id
                    .fetch_max(id + 1, Ordering::Relaxed);
                rebuilder.insert_storage(slot, Arc::new(storage_entry))?;
                expected_storages.remove(&(slot, id));
                rebuilder.processed_slot_count += 1;
            }
            rebuilder.maybe_log_progress(&mut previous_log_time);
        }

        if let Some(path) = split_files.keys().next() {
            return Err(SnapshotError::RebuildStorages(format!(
                "missing matching split storage file for '{}'", path.display(),
            )));
        }
        if let Some(((slot, id), _)) = expected_storages.iter().next() {
            return Err(SnapshotError::RebuildStorages(format!(
                "missing storage files for slot {slot}, id {id}",
            )));
        }
        Ok(rebuilder.storage)
    }

    /// Logs the progress of rebuilding storages, if it has been
    /// `PROGRESS_LOG_INTERVAL` since the previous log.
    fn maybe_log_progress(&self, previous_log_time: &mut Instant) {
        let now = Instant::now();
        if now.duration_since(*previous_log_time) >= PROGRESS_LOG_INTERVAL {
            info!(
                "rebuilt storages for {} slots with {} collisions",
                self.processed_slot_count, self.num_collisions,
            );
            *previous_log_time = now;
        }
    }

    fn insert_storage(
        &mut self,
        slot: Slot,
        storage_entry: Arc<solana_accounts_db::account_storage_entry::AccountStorageEntry>,
    ) -> Result<(), SnapshotError> {
        let storage_id = storage_entry.id();
        if let Some(other) = self.storage.insert(slot, storage_entry) {
            Err(SnapshotError::RebuildStorages(format!(
                "there must be exactly one storage per slot, but slot {slot} has duplicate \
                 storages: {} vs {storage_id}",
                other.id()
            )))
        } else {
            Ok(())
        }
    }
}

/// Get the slot and storage id from an AppendVec or split storage filename.
pub(crate) fn get_slot_and_append_vec_id(filename: &str) -> Result<(Slot, usize), SnapshotError> {
    let storage_name = filename.strip_suffix(".meta")
        .or_else(|| filename.strip_suffix(".data"))
        .unwrap_or(filename);
    let mut parts = storage_name.splitn(2, '.');
    let slot = parts.next().and_then(|s| Slot::from_str(s).ok());
    let id = parts.next().and_then(|s| usize::from_str(s).ok());

    slot.zip(id)
        .ok_or_else(|| SnapshotError::InvalidAppendVecPath(PathBuf::from(filename)))
}
