//! Provides interfaces for rebuilding snapshot storages

use {
    super::SnapshotError,
    crate::serde_snapshot::{SerdeObsoleteAccounts, StorageListItem, remap_append_vec_file},
    agave_fs::FileInfo,
    log::*,
    solana_accounts_db::{
        ObsoleteAccounts,
        account_storage::AccountStorageMap,
        account_storage_entry::AccountStorageEntry,
        accounts_db::{AccountsFileId, AtomicAccountsFileId},
        accounts_file::AccountsFile,
    },
    solana_clock::Slot,
    std::{
        collections::HashMap,
        path::PathBuf,
        str::FromStr as _,
        sync::{Arc, atomic::Ordering},
        time::{Duration, Instant},
    },
};

const PROGRESS_LOG_INTERVAL: Duration = Duration::from_secs(2);

/// Holds state for rebuilding snapshot storages
#[derive(Debug)]
pub(crate) struct SnapshotStorageRebuilder {
    /// Container for storing rebuilt snapshot storages
    storage: AccountStorageMap,
    /// Tracks next append_vec_id
    next_append_vec_id: Arc<AtomicAccountsFileId>,
    /// Tracks the number of collisions in AccountsFileId
    num_collisions: usize,
    /// Number of storage slots that have been rebuilt so far
    processed_slot_count: usize,
}

impl SnapshotStorageRebuilder {
    fn new(next_append_vec_id: Arc<AtomicAccountsFileId>) -> Self {
        Self {
            storage: AccountStorageMap::default(),
            next_append_vec_id,
            num_collisions: 0,
            processed_slot_count: 0,
        }
    }

    /// Rebuilds the account storages from a snapshot archive.
    pub(crate) fn rebuild_storages_from_snapshot_archive(
        files: impl IntoIterator<Item = FileInfo>,
        next_append_vec_id: Arc<AtomicAccountsFileId>,
    ) -> Result<AccountStorageMap, SnapshotError> {
        let mut rebuilder = Self::new(next_append_vec_id);
        let mut previous_log_time = Instant::now();

        for file_info in files {
            let filename = file_info.path.file_name().unwrap().to_str().unwrap();
            if let Ok((slot, id)) = get_slot_and_append_vec_id(filename) {
                if filename.ends_with(".meta") || filename.ends_with(".data") {
                    return Err(SnapshotError::RebuildStorages(
                        "snapshot archives must contain AppendVec storages".to_owned(),
                    ));
                }
                // A snapshot archive only contains storages in AppendVec format.
                // And never contains separate ObsoleteAccounts information.
                // The IDs may overlap though, if the full and incremental snapshots
                // were generated by different nodes.
                let (remapped_id, remapped_file_info) = remap_append_vec_file(
                    slot,
                    id,
                    file_info,
                    &rebuilder.next_append_vec_id,
                    &mut rebuilder.num_collisions,
                )?;
                let accounts_file = AccountsFile::new_for_startup(remapped_file_info)?;
                let storage_entry = AccountStorageEntry::new_existing(
                    slot,
                    remapped_id,
                    accounts_file,
                    ObsoleteAccounts::default(),
                );

                rebuilder.insert_storage(slot, Arc::new(storage_entry))?;
                rebuilder.processed_slot_count += 1;
            }
            rebuilder.maybe_log_progress(&mut previous_log_time);
        }

        Ok(rebuilder.storage)
    }

    /// Rebuilds the account storages from local state.
    pub(crate) fn rebuild_storages_from_local_state(
        files: impl IntoIterator<Item = FileInfo>,
        next_append_vec_id: Arc<AtomicAccountsFileId>,
        mut obsolete_accounts: HashMap<Slot, SerdeObsoleteAccounts>,
        mut expected_storages: HashMap<(Slot, AccountsFileId), StorageListItem>,
    ) -> Result<AccountStorageMap, SnapshotError> {
        let mut rebuilder = Self::new(next_append_vec_id);
        let mut split_files: HashMap<PathBuf, FileInfo> = HashMap::new();
        let mut previous_log_time = Instant::now();

        for file_info in files {
            let filename = file_info.path.file_name().unwrap().to_str().unwrap();
            if let Ok((slot, id)) = get_slot_and_append_vec_id(filename) {
                let id = AccountsFileId::try_from(id).unwrap();
                let expected = expected_storages.get(&(slot, id)).copied()
                    .filter(|item| item.matches_filename(filename))
                    .ok_or_else(|| SnapshotError::RebuildStorages(format!(
                        "unexpected storage file '{}'", file_info.path.display(),
                    )))?;
                let (meta, data) = match expected {
                    StorageListItem::AppendVec { .. } => (file_info, None),
                    StorageListItem::Split { has_data_file: false, .. } => (file_info, None),
                    StorageListItem::Split { has_data_file: true, .. } => {
                        let base_path = file_info.path.with_extension("");
                        let Some(other) = split_files.remove(&base_path) else {
                            split_files.insert(base_path, file_info);
                            rebuilder.maybe_log_progress(&mut previous_log_time);
                            continue;
                        };
                        if filename.ends_with(".meta") {
                            (file_info, Some(other))
                        } else {
                            (other, Some(file_info))
                        }
                    }
                };
                // Validate obsolete accounts before opening either storage format.
                let obsolete_accounts = obsolete_accounts.remove(&slot).map(|accounts| accounts.into_tuple());
                let obsolete_accounts =
                    if let Some((obsolete_accounts, obsolete_id, _bytes)) = obsolete_accounts {
                        if obsolete_id != id {
                            return Err(SnapshotError::MismatchedAccountsFileId(id, obsolete_id));
                        }
                        obsolete_accounts
                    } else {
                        ObsoleteAccounts::default()
                    };
                let accounts_file = match expected {
                    StorageListItem::AppendVec { .. } => AccountsFile::new_for_startup(meta)?,
                    StorageListItem::Split { .. } => AccountsFile::new_split_for_startup(meta, data)?,
                };
                let storage_entry =
                    AccountStorageEntry::new_existing(slot, id, accounts_file, obsolete_accounts);

                // Keep track of the highest append_vec_id in the system, so the future append_vecs
                // can be assigned to unique IDs.  This is only needed when loading from local
                // state.  When loading from a snapshot archive, the max of the appendvec IDs is
                // updated in remap_append_vec_file(), which is not in the from_local_state route.
                rebuilder
                    .next_append_vec_id
                    .fetch_max(id + 1, Ordering::Relaxed);
                rebuilder.insert_storage(slot, Arc::new(storage_entry))?;
                expected_storages.remove(&(slot, id));
                rebuilder.processed_slot_count += 1;
            }
            rebuilder.maybe_log_progress(&mut previous_log_time);
        }

        if let Some(path) = split_files.keys().next() {
            return Err(SnapshotError::RebuildStorages(format!(
                "missing matching split storage file for '{}'", path.display(),
            )));
        }
        if let Some(((slot, id), _)) = expected_storages.iter().next() {
            return Err(SnapshotError::RebuildStorages(format!(
                "missing storage files for slot {slot}, id {id}",
            )));
        }
        Ok(rebuilder.storage)
    }

    /// Logs the progress of rebuilding storages, if it has been
    /// `PROGRESS_LOG_INTERVAL` since the previous log.
    fn maybe_log_progress(&self, previous_log_time: &mut Instant) {
        let now = Instant::now();
        if now.duration_since(*previous_log_time) >= PROGRESS_LOG_INTERVAL {
            info!(
                "rebuilt storages for {} slots with {} collisions",
                self.processed_slot_count, self.num_collisions,
            );
            *previous_log_time = now;
        }
    }

    fn insert_storage(
        &mut self,
        slot: Slot,
        storage_entry: Arc<solana_accounts_db::account_storage_entry::AccountStorageEntry>,
    ) -> Result<(), SnapshotError> {
        let storage_id = storage_entry.id();
        if let Some(other) = self.storage.insert(slot, storage_entry) {
            Err(SnapshotError::RebuildStorages(format!(
                "there must be exactly one storage per slot, but slot {slot} has duplicate \
                 storages: {} vs {storage_id}",
                other.id()
            )))
        } else {
            Ok(())
        }
    }
}

/// Get the slot and storage id from an AppendVec or split storage filename.
pub(crate) fn get_slot_and_append_vec_id(filename: &str) -> Result<(Slot, usize), SnapshotError> {
    let storage_name = filename.strip_suffix(".meta")
        .or_else(|| filename.strip_suffix(".data"))
        .unwrap_or(filename);
    let mut parts = storage_name.splitn(2, '.');
    let slot = parts.next().and_then(|s| Slot::from_str(s).ok());
    let id = parts.next().and_then(|s| usize::from_str(s).ok());

    slot.zip(id)
        .ok_or_else(|| SnapshotError::InvalidAppendVecPath(PathBuf::from(filename)))
}

#[cfg(test)]
mod tests {
    use {
        super::*,
        crate::serde_snapshot::SerdeObsoleteAccountsMap,
        solana_account::AccountSharedData,
        solana_accounts_db::{
            ObsoleteAccountItem, ObsoleteAccounts,
            account_storage_entry::AccountStorageEntry,
            accounts_file::{AccountsFile, AccountsFileProvider},
        },
        solana_pubkey::Pubkey,
        test_case::test_case,
    };

    #[test]
    fn test_get_slot_and_append_vec_id() {
        let expected_slot = 12345;
        let expected_id = 9987;
        let (slot, id) =
            get_slot_and_append_vec_id(&AccountsFile::file_name(expected_slot, expected_id))
                .unwrap();
        assert_eq!(expected_slot, slot);
        assert_eq!(expected_id as usize, id);
        for suffix in ["meta", "data"] {
            assert_eq!(
                get_slot_and_append_vec_id(&format!("{expected_slot}.{expected_id}.{suffix}")).unwrap(),
                (expected_slot, expected_id as usize),
            );
        }
        assert!(get_slot_and_append_vec_id("12345.9987.other").is_err());
    }

    #[test_case(false)]
    #[test_case(true)]
    fn test_rebuild_mixed_storages(data_first: bool) {
        let dir = tempfile::tempdir().unwrap();
        let slot = 123;
        let id = 456;
        let split = AccountsFileProvider::Split.new_writable(
            dir.path().join(AccountsFile::file_name(slot, id)), 0,
        ).unwrap();
        let owner = Pubkey::new_unique();
        let accounts = vec![
            (Pubkey::new_unique(), AccountSharedData::new(1, 165, &owner)),
            (Pubkey::new_unique(), AccountSharedData::new(2, 8192, &owner)),
        ];
        let offsets = split.write_accounts(&(slot, accounts.as_slice())).unwrap().offsets;
        split.disable_remove_on_drop();
        split.flush().unwrap();
        let obsolete = ObsoleteAccounts {
            accounts: vec![ObsoleteAccountItem {
                offset: offsets[1],
                data_len: 8192,
                slot: slot + 1,
            }],
        };
        let append_vec = Arc::new(AccountStorageEntry::new(
            dir.path(), slot + 1, id + 1, 16384, AccountsFileProvider::AppendVec,
        ));
        append_vec.accounts.write_accounts(&(slot + 1, accounts.as_slice())).unwrap();
        append_vec.flush().unwrap();
        let av = FileInfo::new_from_path(append_vec.path()).unwrap();
        let split = Arc::new(AccountStorageEntry::new_existing(
            slot, id, split, obsolete,
        ));
        let manifest = crate::serde_snapshot::StoragesList::new_from_storages(
            &[split.clone(), append_vec.clone()],
        ).into_map();
        let obsolete_accounts = SerdeObsoleteAccountsMap::new_from_storages(
            &[split.clone(), append_vec.clone()], slot + 1,
        );
        let meta = FileInfo::new_from_path(split.path()).unwrap();
        let data = FileInfo::new_from_path(dir.path().join(format!("{slot}.{id}.data"))).unwrap();
        split.disable_remove_on_drop();
        append_vec.disable_remove_on_drop();
        drop(split);
        drop(append_vec);
        let files = if data_first { vec![data, av, meta] } else { vec![meta, av, data] };
        let next_id = Arc::new(AtomicAccountsFileId::new(0));
        let storages = SnapshotStorageRebuilder::rebuild_storages_from_local_state(
            files, next_id.clone(), obsolete_accounts.into_hashmap(), manifest,
        ).unwrap();
        assert_eq!(storages.len(), 2);
        assert_eq!(next_id.load(Ordering::Relaxed), id + 2);
        let storage = storages.get(&slot).unwrap();
        assert!(matches!(storage.accounts, AccountsFile::Split(_)));
        for (offset, (_, account)) in offsets.iter().zip(&accounts) {
            let loaded = storage.accounts.get_stored_account_callback(*offset, |stored| {
                solana_accounts_db::utils::create_account_shared_data(&stored)
            }).unwrap();
            assert_eq!(&loaded, account);
        }
        let obsolete = storage.obsolete_accounts_for_snapshots(slot + 1);
        assert_eq!(obsolete.accounts.len(), 1);
        assert_eq!(obsolete.accounts[0].offset, offsets[1]);
        assert_eq!(obsolete.accounts[0].data_len, 8192);
        assert!(matches!(storages.get(&(slot + 1)).unwrap().accounts, AccountsFile::AppendVec(_)));
    }

    #[test_case("meta")]
    #[test_case("data")]
    fn test_archive_rejects_split_files(suffix: &str) {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join(format!("123.456.{suffix}"));
        std::fs::write(&path, b"not an AppendVec").unwrap();
        let result = SnapshotStorageRebuilder::rebuild_storages_from_snapshot_archive(
            [FileInfo::new_from_path(path).unwrap()],
            Arc::new(AtomicAccountsFileId::new(0)),
        );
        assert!(matches!(result, Err(SnapshotError::RebuildStorages(message))
            if message == "snapshot archives must contain AppendVec storages"));
    }

    #[test]
    fn test_rebuild_split_missing_meta_file() {
        let dir = tempfile::tempdir().unwrap();
        let split = AccountsFileProvider::Split.new_writable(dir.path().join("123.456"), 0).unwrap();
        let accounts = [(Pubkey::new_unique(), AccountSharedData::new(1, 8192, &Pubkey::default()))];
        split.write_accounts(&(123, accounts.as_slice())).unwrap();
        split.disable_remove_on_drop();
        split.flush().unwrap();
        let file = FileInfo::new_from_path(dir.path().join("123.456.data")).unwrap();
        let result = SnapshotStorageRebuilder::rebuild_storages_from_local_state(
            [file], Arc::new(AtomicAccountsFileId::new(0)), HashMap::new(),
            HashMap::from([((123, 456), StorageListItem::Split {
                slot: 123, id: 456, has_data_file: true,
            })]),
        );
        assert!(matches!(result, Err(SnapshotError::RebuildStorages(message))
            if message.contains("missing matching split storage file")));
    }

    #[test]
    fn test_rebuild_split_without_data_file() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("123.456");
        let split = AccountsFileProvider::Split.new_writable(&path, 0).unwrap();
        let accounts = [(Pubkey::new_unique(), AccountSharedData::new(1, 165, &Pubkey::default()))];
        let offsets = split.write_accounts(&(123, accounts.as_slice())).unwrap().offsets;
        split.disable_remove_on_drop();
        split.flush().unwrap();
        let file = FileInfo::new_from_path(split.path()).unwrap();
        drop(split);
        assert!(!dir.path().join("123.456.data").exists());
        let next_id = Arc::new(AtomicAccountsFileId::new(0));
        let storages = SnapshotStorageRebuilder::rebuild_storages_from_local_state(
            [file], next_id.clone(), HashMap::new(),
            HashMap::from([((123, 456), StorageListItem::Split {
                slot: 123, id: 456, has_data_file: false,
            })]),
        ).unwrap();
        assert_eq!(next_id.load(Ordering::Relaxed), 457);
        let storage = storages.get(&123).unwrap();
        let loaded = storage.accounts.get_stored_account_callback(offsets[0], |account| {
            solana_accounts_db::utils::create_account_shared_data(&account)
        }).unwrap();
        assert_eq!(loaded, accounts[0].1);
    }

    #[test_case(AccountsFileProvider::AppendVec)]
    #[test_case(AccountsFileProvider::Split)]
    fn test_rebuild_local_state_checks_obsolete_id_before_opening(provider: AccountsFileProvider) {
        let dir = tempfile::tempdir().unwrap();
        let (name, item) = match provider {
            AccountsFileProvider::AppendVec => (
                "123.456", StorageListItem::AppendVec { slot: 123, id: 456 },
            ),
            AccountsFileProvider::Split => (
                "123.456.meta", StorageListItem::Split { slot: 123, id: 456, has_data_file: false },
            ),
        };
        let path = dir.path().join(name);
        std::fs::write(&path, b"invalid storage; must validate obsolete ID before opening").unwrap();
        let result = SnapshotStorageRebuilder::rebuild_storages_from_local_state(
            [FileInfo::new_from_path(path).unwrap()],
            Arc::new(AtomicAccountsFileId::new(0)),
            HashMap::from([(123, SerdeObsoleteAccounts { id: 457, bytes: 0, accounts: vec![] })]),
            HashMap::from([((123, 456), item)]),
        );
        assert!(matches!(result, Err(SnapshotError::MismatchedAccountsFileId(456, 457))));
    }

    #[test]
    fn test_manifest_requires_data_file() {
        let dir = tempfile::tempdir().unwrap();
        let split = AccountsFileProvider::Split.new_writable(dir.path().join("123.456"), 0).unwrap();
        let meta = FileInfo::new_from_path(split.path()).unwrap();
        let result = SnapshotStorageRebuilder::rebuild_storages_from_local_state(
            [meta], Arc::new(AtomicAccountsFileId::new(0)), HashMap::new(),
            HashMap::from([((123, 456), StorageListItem::Split {
                slot: 123, id: 456, has_data_file: true,
            })]),
        );
        assert!(matches!(result, Err(SnapshotError::RebuildStorages(message))
            if message.contains("missing matching split storage file")));
    }

    #[test]
    fn test_manifest_requires_missing_storage() {
        let result = SnapshotStorageRebuilder::rebuild_storages_from_local_state(
            [], Arc::new(AtomicAccountsFileId::new(0)), HashMap::new(),
            HashMap::from([((123, 456), StorageListItem::AppendVec { slot: 123, id: 456 })]),
        );
        assert!(matches!(result, Err(SnapshotError::RebuildStorages(message))
            if message.contains("missing storage files for slot 123, id 456")));
    }

    #[test]
    fn test_manifest_does_not_infer_data_file_from_disk() {
        let dir = tempfile::tempdir().unwrap();
        let split = AccountsFileProvider::Split.new_writable(dir.path().join("123.456"), 0).unwrap();
        std::fs::write(dir.path().join("123.456.data"), b"not a data file").unwrap();
        let meta = FileInfo::new_from_path(split.path()).unwrap();
        let manifest = HashMap::from([((123, 456), StorageListItem::Split {
            slot: 123, id: 456, has_data_file: false,
        })]);
        let storages = SnapshotStorageRebuilder::rebuild_storages_from_local_state(
            [meta], Arc::new(AtomicAccountsFileId::new(0)), HashMap::new(), manifest,
        ).unwrap();
        assert!(matches!(&storages.get(&123).unwrap().accounts, AccountsFile::Split(file)
            if file.data_file().is_none()));
    }
}
